apiVersion: v1
kind: Pod
metadata:
  name: express-test
  labels:
    app: express-test
spec:
  containers:
  - name: express-test
    image: lukondefmwila/express-test:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080